### ISSUE TITLE
Circuit

### ISSUE THREAD

**Issue by benevpi** [OliWright/PicoVectorscopeExamples#1]
Do you have a schematic or circuit diagram for this? I've had a go at re-creating it from your youtube video, but it's not working and it might be that I've not got the circuit quite right.

**Comment by OliWright** [comment]
Oh - I've not made up schematics yet - but I can try to help you get it
working.  Are you using the same DACs?

**Comment by Oli-Wright** [comment]
I've made a [preliminary schematic](https://github.com/OliWright/PicoVectorscope/blob/main/PicoVectorscopeSchematic.pdf), but it's untested.  I think it's right though.
The main complication is I the DACs need positive and negative voltages.  There might be a way to wire them up so that they don't, but I couldn't figure it out.  So I'm using a PC power supply, which provides +-12v for the DACs, along with 5v for the Pico.
